In [74]:
pip list

Package                                  Version
---------------------------------------- -------------------
absl-py                                  1.4.0
accelerate                               1.12.0
access                                   1.1.9
affine                                   2.4.0
aiofiles                                 24.1.0
aiohappyeyeballs                         2.6.1
aiohttp                                  3.13.2
aiosignal                                1.4.0
aiosqlite                                0.21.0
alabaster                                1.0.0
albucore                                 0.0.24
albumentations                           2.0.8
ale-py                                   0.11.2
alembic                                  1.17.2
altair                                   5.5.0
annotated-types                          0.7.0
antlr4-python3-runtime                   4.9.3
anyio                                    4.12.0
anywidget                           

In [75]:
pip install panda

In [76]:
import pandas as pd
name=pd.DataFrame({
    'name':[1,2,3,4,5,6,7,8,91,0],
    'age':[1,2,3,4,5,6,7,8,9,0]
})

In [77]:
print(name)

   name  age
0     1    1
1     2    2
2     3    3
3     4    4
4     5    5
5     6    6
6     7    7
7     8    8
8    91    9
9     0    0


In [78]:
print(dir(pd))

['ArrowDtype', 'BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_built_with_meson', '_config', '_is_numpy_dev', '_libs', '_pandas_datetime_CAPI', '_pandas_parser_CAPI', '_testing', '_typing', '_version_meson', 'annotations', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'conca

In [79]:
age=pd.Series(['harsha','hhhh','alice'])
print(age)

0    harsha
1      hhhh
2     alice
dtype: object


In [80]:
import torch

In [81]:
a=torch.randn(1,100,requires_grad=True)

In [82]:
a

tensor([[-0.0493, -0.5248,  0.8926, -0.3900,  0.9289, -1.2709, -0.9656,  0.5657,
          0.8328,  2.0574, -0.2734,  1.1275, -1.4747, -1.8436, -0.4609,  1.9263,
         -0.1457,  0.5909,  1.2134, -1.4905, -0.8808,  0.6816, -0.6848,  0.8497,
         -0.2606,  1.0406, -1.9795,  0.9962, -0.4489, -0.0269, -1.0666,  1.1699,
          0.8118, -0.3509, -0.6933,  0.2831, -0.9518,  0.0302, -0.3415, -0.7537,
         -0.5792, -1.2852,  0.7913,  1.1701, -0.2749,  0.2346,  0.9782, -0.6856,
         -0.1231, -0.4181,  0.2061, -0.9168,  0.4612,  2.6005, -0.9906,  0.0300,
         -0.1785,  0.6177, -1.1388, -1.0667,  1.9170, -0.2932,  0.4341,  0.4049,
          1.0427,  1.0814, -0.1235, -1.2381,  2.0614, -1.0538, -1.1999, -0.8085,
         -1.1381,  0.4203, -0.3441,  0.2355,  0.3478, -0.8085, -0.3225, -0.5019,
         -0.2556,  0.0133, -0.5954,  0.3127,  0.0723, -0.6097,  0.6315, -0.2272,
          0.8800,  1.4365,  0.2087, -0.8541,  0.1284, -0.5635,  0.5875,  1.0655,
          1.4102, -0.1561, -

In [83]:
b=torch.randn(1,100)

In [84]:
b

tensor([[ 0.0907,  0.0503, -0.6924, -0.4866, -0.1484, -1.6819,  0.7740,  0.5092,
         -1.2159, -1.3564, -0.7913, -1.5392, -1.0056, -0.8997,  0.4787,  0.6248,
          0.2671,  1.6003,  0.1287,  1.0422,  1.0343, -0.9627, -0.5141,  1.1440,
          0.5149, -1.9159, -0.5294,  0.2707,  1.1895, -1.8108, -1.5409, -0.3634,
         -1.2510,  1.3571,  0.0528, -0.6355, -0.3881,  0.2912, -2.3617, -0.7497,
         -1.5116,  0.1484,  0.1316, -0.9311, -0.0547, -0.9642, -1.8363, -1.2042,
         -0.5997,  0.0395,  0.1336,  0.7565,  1.4999,  2.0499,  1.7998, -0.1997,
         -0.9441,  1.1238,  1.5964, -0.0478,  1.1590,  1.5237, -0.5783,  1.4351,
         -1.3584, -0.1006, -1.3633,  0.6923,  0.0092,  0.3895, -1.3477, -0.5520,
         -1.6221, -0.7460,  0.4665, -1.3538,  1.0013, -2.0119, -0.4242, -1.2022,
         -0.8477,  1.9783,  1.0287, -1.3532, -0.3821, -0.9263, -0.4952,  0.1751,
          1.8127, -1.5499, -0.2290, -0.5726,  1.1649, -0.3161,  1.3036,  1.5518,
         -0.1018, -0.9101,  

In [85]:
from numpy._core.numeric import ones
c=torch.ones(1,100)

In [86]:
c

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [87]:
d=torch.ones(1,100,requires_grad=True)

In [88]:
d

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], requires_grad=True)

In [89]:
d=a+b-c

In [90]:
d

tensor([[-0.9586, -1.4745, -0.7998, -1.8766, -0.2195, -3.9528, -1.1916,  0.0749,
         -1.3830, -0.2990, -2.0646, -1.4117, -3.4803, -3.7433, -0.9821,  1.5511,
         -0.8785,  1.1913,  0.3421, -1.4483, -0.8465, -1.2811, -2.1989,  0.9937,
         -0.7458, -1.8753, -3.5089,  0.2669, -0.2594, -2.8378, -3.6075, -0.1936,
         -1.4393,  0.0062, -1.6405, -1.3523, -2.3399, -0.6786, -3.7032, -2.5033,
         -3.0908, -2.1368, -0.0772, -0.7610, -1.3296, -1.7296, -1.8581, -2.8898,
         -1.7227, -1.3786, -0.6603, -1.1603,  0.9611,  3.6504, -0.1908, -1.1697,
         -2.1225,  0.7414, -0.5424, -2.1145,  2.0759,  0.2306, -1.1442,  0.8400,
         -1.3157, -0.0192, -2.4868, -1.5457,  1.0706, -1.6643, -3.5476, -2.3605,
         -3.7602, -1.3258, -0.8776, -2.1183,  0.3492, -3.8204, -1.7467, -2.7041,
         -2.1033,  0.9916, -0.5667, -2.0406, -1.3098, -2.5361, -0.8637, -1.0521,
          1.6926, -1.1134, -1.0203, -2.4268,  0.2932, -1.8795,  0.8912,  1.6173,
          0.3084, -2.0662, -

In [91]:
print(d.grad_fn,
a.grad_fn,
b.grad_fn)

<SubBackward0 object at 0x7ee315bbc730> None None


In [92]:
c=torch.randn(2,2, requires_grad=True)

In [93]:
d=torch.randn(2,2,requires_grad=True)

In [94]:
c@d

tensor([[-0.2329, -0.7715],
        [ 0.2854,  0.6833]], grad_fn=<MmBackward0>)

In [95]:
x=torch.randn(10,10, requires_grad=True)
w=torch.randn(10,10, requires_grad=True)
b=torch.randn(10,10,requires_grad=True)
y_hat=x@w+b
print(y_hat)
print(w.grad)
print(b.grad)

tensor([[-0.0635, -0.6938,  1.1671,  0.9592,  0.0527,  2.3561, -0.7539, -0.8246,
         -1.3230,  0.1506],
        [ 1.4593, -1.6744,  3.7099,  1.6050,  1.6052,  0.9354, -2.6219, -0.9426,
         -0.0657, -0.3263],
        [ 1.6894,  2.4598, -0.9430,  0.7204,  2.0566,  3.3916,  0.2595,  1.9987,
         -0.4953,  2.2583],
        [ 1.7957,  4.1636,  4.1818, -7.9570,  2.9042, -4.0745, -4.5228, -1.6497,
          4.0146, -1.4607],
        [-1.0511, -0.1797,  2.5407, -0.3338, -3.5702,  3.2805,  0.4457,  2.4331,
         -0.3039, -2.9719],
        [ 2.3349,  4.1167,  1.6939, -1.6215,  2.0849, -3.6106,  0.5086, -0.2815,
          4.7604, -0.2761],
        [-0.2619,  0.1148, -0.6786,  4.2345,  1.8594,  2.1330,  0.4555,  2.5169,
         -1.8088,  3.3907],
        [ 1.3457,  5.0714,  3.4335, -4.5155,  1.8615,  4.2054, -2.5195,  4.1050,
          9.1973,  3.5681],
        [-5.2940, -2.9934, -9.2745,  0.3571, -3.6144, -0.9493,  4.5526,  2.8218,
         -0.4013,  2.8859],
        [ 2.1784, -

###linearDeepmodel start
*input and real output

In [96]:
import torch
import torch.nn as nn
torch.manual_seed(100)
X=torch.randn(2,2)
Y=torch.randn(2,2)

##Model

In [97]:
class model(nn.Module):
  def __init__(self):
    super().__init__()
    # Layer 1: Input (1) -> Hidden (2)
    self.linear1 = nn.Linear(2, 2)
    self.hidden_act = nn.SELU()
    # Layer 2: Hidden (2) -> Output (1)
    self.output_linear = nn.Linear(2, 2)

  def forward(self, x):
    # Pass through the first layer
    x = self.linear1(x)
    # Apply activation
    x = self.hidden_act(x)
    # Pass through the output layer
    x = self.output_linear(x)
    return x

###Training Loop

In [98]:
Model=model()
learning_rate=0.2

In [99]:
epoach=100
optimer=torch.optim.SGD(Model.parameters(),learning_rate)
critian=nn.MSELoss()

In [100]:
from typing import ItemsView
for epoah in range(epoach):
  Y_hat=Model(X)
  loss=critian(Y_hat,Y)
  optimer.zero_grad()
  loss.backward()
  optimer.step()
  print(Model.state_dict())

OrderedDict({'linear1.weight': tensor([[ 0.7042,  0.3614],
        [-0.4424, -0.2277]]), 'linear1.bias': tensor([-0.4461, -0.0096]), 'output_linear.weight': tensor([[0.2521, 0.5361],
        [0.1477, 0.4518]]), 'output_linear.bias': tensor([ 0.0501, -0.4030])})
OrderedDict({'linear1.weight': tensor([[ 0.6815,  0.3802],
        [-0.5133, -0.1693]]), 'linear1.bias': tensor([-0.5312, -0.2713]), 'output_linear.weight': tensor([[0.3255, 0.5549],
        [0.2595, 0.4780]]), 'output_linear.bias': tensor([-0.0946, -0.6189])})
OrderedDict({'linear1.weight': tensor([[ 0.6541,  0.4014],
        [-0.5649, -0.1298]]), 'linear1.bias': tensor([-0.5936, -0.3720]), 'output_linear.weight': tensor([[0.3548, 0.5975],
        [0.3255, 0.5512]]), 'output_linear.bias': tensor([-0.1552, -0.7381])})
OrderedDict({'linear1.weight': tensor([[ 0.6265,  0.4220],
        [-0.6192, -0.0907]]), 'linear1.bias': tensor([-0.6303, -0.4030]), 'output_linear.weight': tensor([[0.3597, 0.6282],
        [0.3576, 0.6114]]), 'ou

#Manual InearRegression

In [101]:
import torch
X=torch.randn(10,10)
Y=torch.randn(10,10)
learning_rate=0.1

###weights&Bias

In [102]:
w=torch.randn(10,10,requires_grad=True)
b=torch.randn(10,10,requires_grad=True)

####Training Loop

In [103]:
from os import stat_result
from numpy import mean
epoach=1000
for epoch in range(epoach):
  Y_hat=X@w+b
  Loss=((Y_hat-Y)**2).mean()
  Loss.backward()
  with torch.no_grad():
    w-=learning_rate*w.grad
    b-=learning_rate*b.grad
    # w.grad.zero_()
    # b.grad.zero_()
    if epoch % 10 == 0:
      print(f'Epoch {epoch}, Loss: {Loss.item()}')
    w.grad.zero_()
    b.grad.zero_()

Epoch 0, Loss: 9.047229766845703
Epoch 10, Loss: 4.343796253204346
Epoch 20, Loss: 2.583679437637329
Epoch 30, Loss: 1.8103107213974
Epoch 40, Loss: 1.3993090391159058
Epoch 50, Loss: 1.139593482017517
Epoch 60, Loss: 0.9543498754501343
Epoch 70, Loss: 0.8125619292259216
Epoch 80, Loss: 0.6997993588447571
Epoch 90, Loss: 0.6081691384315491
Epoch 100, Loss: 0.5326855182647705
Epoch 110, Loss: 0.4698657989501953
Epoch 120, Loss: 0.4171285331249237
Epoch 130, Loss: 0.37249815464019775
Epoch 140, Loss: 0.3344362676143646
Epoch 150, Loss: 0.3017328679561615
Epoch 160, Loss: 0.27343007922172546
Epoch 170, Loss: 0.2487652748823166
Epoch 180, Loss: 0.22712863981723785
Epoch 190, Loss: 0.20802992582321167
Epoch 200, Loss: 0.19107326865196228
Epoch 210, Loss: 0.1759372353553772
Epoch 220, Loss: 0.16235949099063873
Epoch 230, Loss: 0.1501244306564331
Epoch 240, Loss: 0.13905417919158936
Epoch 250, Loss: 0.1290007084608078
Epoch 260, Loss: 0.11984025686979294
Epoch 270, Loss: 0.11146854609251022
E

##Testing

In [104]:
Y_test=torch.randn(10,10)
Loss=((Y_hat-Y_test)**2).mean()
print(Loss)

tensor(1.9405, grad_fn=<MeanBackward0>)


####Load the data set in pytrorch

In [105]:
from torch.utils.data import Dataset,DataLoader

##create a dataset

In [106]:
from sklearn.datasets import load_iris
x,y=load_iris(return_X_y=True)

In [107]:
class dataset(Dataset):
  def __init__(self,x,y):
    self.X=x
    self.Y=y
  def __len__(self):
    return len(self.X)
  def __getitem__(self,idx):
    return self.X[idx],self.Y[idx]
data=dataset(x,y)

####load data set and shuffle and batch size

In [108]:
train_loader = DataLoader(
    dataset=data,
    batch_size=16,
    shuffle=True,
    num_workers=0
)

##Model Creation

In [109]:
import torch.nn as nn
class model(nn.Module):
  def __init__(self):
    super().__init__()
    # Layer 1: Input (4 features from Iris) -> Hidden (10)
    # If you want to use Conv2d, the input shape (4 features) is not suitable.
    # Conv2d expects input like (batch_size, channels, height, width).
    # For tabular data, nn.Linear is the correct choice.
    self.linear1 = nn.Linear(4, 10) # Keeping Linear as it's appropriate for Iris data
    self.hidden_act = nn.SELU()
    # Layer 2: Hidden (10) -> Output (3 classes for Iris)
    self.output_linear = nn.Linear(10, 3)

  def forward(self, x):
    # Pass through the first layer
    x = self.linear1(x)
    # Apply activation
    x = self.hidden_act(x)
    # Pass through the output layer
    x = self.output_linear(x)
    return x

##Load the mosdel in mdl

In [110]:
mdl=model()
criterian= nn.CrossEntropyLoss()
optimer=torch.optim.Adam(mdl.parameters(),learning_rate)

###Training loop

In [114]:
epoach = 100
for ep in range(epoach):
  for infeature , target in train_loader:
    # Cast input features to float32 to match model's expected dtype
    infeature = infeature.float()
    # Cast target to long for CrossEntropyLoss
    target = target.long()
    y_hat=mdl(infeature)
    loss=criterian(y_hat,target)
    optimer.zero_grad()
    loss.backward()
    optimer.step()
    print(f'{loss.item()}')

0.015179120935499668
0.000557443592697382
0.06999624520540237
0.030748872086405754
0.017905207350850105
0.265324205160141
0.0006360934348776937
0.0005111685022711754
0.13237306475639343
9.260006481781602e-05
0.07366865128278732
0.06133122742176056
0.02289622649550438
0.0007410217076539993
0.03926569223403931
0.010200858116149902
0.011586707085371017
0.18327555060386658
0.03855793923139572
6.422156729968265e-05
0.010648176074028015
0.0091245723888278
0.0001547846186440438
0.0024195469450205564
0.2822730541229248
0.03534932807087898
0.06710115075111389
0.0005124687450006604
0.09790664911270142
9.77065647020936e-05
0.030158238485455513
0.006079363636672497
0.175890251994133
0.04426676407456398
0.07957956939935684
0.002191034145653248
0.0041823675855994225
0.11029975861310959
0.3008268475532532
0.0017241626046597958
0.0011448697187006474
0.029199475422501564
0.029978979378938675
0.00020599235722329468
0.031784579157829285
0.02365873195230961
0.006772665306925774
0.004920496139675379
0.2929